### ISSUE TITLE
Distorted image 

### ISSUE THREAD

**Issue by MakerLab-Vector** [schlae/scopetrex#2]
Hello! You have created a masterpiece! But I have issues with it. I want to build my own Vectrex with electromagnetic crt with audio amplifier like in your CRT-Driver project. It works decent, but not with Scopetrex. Digital part of Scopetrex works good but analog is messed. I also tried it on oscilloscope but it was looking just the same. DAC adjust does not help.All components are same but 4700pf capacitors were changed with 0.01μF ones like in original Vectrex schematic. Replacing them with lower values seems doesn't doing too much. I guess the problem in op amps. I used TL072 and TL074 from STM instead of LFs because I couldn't find them. Their electrical characteristics absolutely same but simplified schematic is different. Maybe that's the reason. Can You please try to replace LFs with TLs and say if it's the reason? Thank You for help!

**Comment by MakerLab-Vector** [comment]
Solved

**Comment by rothkane** [comment]
> Solved

How was this solved as I have the same issue with a distorted screen but mines using LF opamps

**FIXED** had a faulty op amp the top right one, U304B LF353, replaced with a tl082 worked fine.
